services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: questboard_db
      POSTGRES_USER: questboard
      POSTGRES_PASSWORD: questboard_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U questboard -d questboard_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 questboard.asgi:application"
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DEBUG: "True"
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: questboard_db
      DB_USER: questboard
      DB_PASSWORD: questboard_pass
      DB_HOST: db
      DB_PORT: "5432"
      REDIS_HOST: redis
      # Email (SMTP Mail.ru)
      EMAIL_HOST: smtp.mail.ru
      EMAIL_PORT: "465"
      EMAIL_USE_SSL: "True"
      EMAIL_HOST_USER: questboard@mail.ru
      EMAIL_HOST_PASSWORD: sW4Oj6V56Ip4nHlpNdb5

volumes:
  postgres_data: