# Generated by Django 6.1.1 on 2026-09-11 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='achievements.achievement', verbose_name='Ачивка'),
        ),
    ]
